[package]
name = "api-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
kafka = "0.10.0"
rust_decimal = "1.37.2"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.143"
